server:
  port: 6060
spring:
  sql:
    init:
      mode: always # ensures that the DB is populated data from data.sql
      platform: postgresql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: debug
