spring:
  application:
    name: Vehicle
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7432/vehicle
    username: vehicle
    password: 4c9435c2955f0cc2b7c5